
spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.64.3
    port: 5672
    username: admin
    password: admin

server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

zuul:
  retryable: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        

        
        
